<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 05 Feb 2014 13:21:30 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'analytics_googleanalytics' => 
  array (
    'is_setup' => '1',
    'trackingcode' => ' <script type="text/javascript">



  var _gaq = _gaq || [];

  _gaq.push([\'_setAccount\', \'UA-39058625-1\']);

  _gaq.push([\'_trackPageview\']);



  (function() {

    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;

    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';

    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);

  })();



</script>',
  ),
);
