<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Fri, 21 Mar 2014 15:56:08 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_paypal' => 
  array (
    'is_setup' => '1',
    'displayname' => 'PayPal',
    'email' => 'tesoreriadp@intima.com.mx',
    'testmode' => 'NO',
  ),
);
