<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 05 Feb 2014 13:21:22 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'currencyid' => '1',
    'currencycountryid' => '1',
    'currencycouregid' => NULL,
    'currencycode' => 'MXN',
    'currencyconvertercode' => NULL,
    'currencyname' => 'PESOS',
    'currencyexchangerate' => '1.0000000000',
    'currencystring' => '$',
    'currencystringposition' => 'LEFT',
    'currencydecimalstring' => '.',
    'currencythousandstring' => ',',
    'currencydecimalplace' => '2',
    'currencylastupdated' => '1391024899',
    'currencyisdefault' => '1',
    'currencystatus' => '1',
  ),
  'default' => '1',
);
