<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 05 Feb 2014 13:21:22 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'customergroupid' => '1',
    'groupname' => 'Asesoras',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  2 => 
  array (
    'customergroupid' => '2',
    'groupname' => 'Tiendas Propias',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  3 => 
  array (
    'customergroupid' => '3',
    'groupname' => 'Distribuidores',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  'default' => '4',
  4 => 
  array (
    'customergroupid' => '4',
    'groupname' => 'Clientes Finales',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '1',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
);
