<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 05 Feb 2014 13:21:26 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => '1',
  1 => '1',
  2 => '1',
  3 => '1',
  4 => '1',
);
