<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 02 Apr 2014 12:48:42 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'emailintegration_mailchimp' => 
  array (
    'apikey' => '67d83e77c6a6a3c5e018f7e807d254b2-us5',
    'isconfigured' => '1',
    'last_list_update' => '1392084973',
  ),
);
