<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Tue, 25 Mar 2014 10:56:54 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'latest' => 'Unknown',
  'lastCheck' => 1395766614,
);
