<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 02 Apr 2014 13:26:57 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  '' => 
  array (
  ),
  'livechat_custom' => 
  array (
    'is_setup' => '1',
    'livechatcode' => '<!-- ClickDesk Live Chat Service for websites -->
<script type=\'text/javascript\'>
var _glc =_glc || []; _glc.push(\'all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGIyorwQM\');
var glcpath = ((\'https:\' == document.location.protocol) ? \'https://my.clickdesk.com/clickdesk-ui/browser/\' : 
\'http://my.clickdesk.com/clickdesk-ui/browser/\');
var glcp = ((\'https:\' == document.location.protocol) ? \'https://\' : \'http://\');
var glcspt = document.createElement(\'script\'); glcspt.type = \'text/javascript\'; 
glcspt.async = true; glcspt.src = glcpath + \'livechat-new.js\';
var s = document.getElementsByTagName(\'script\')[0];s.parentNode.insertBefore(glcspt, s);
</script>
<!-- End of ClickDesk -->',
    'position' => 'header',
  ),
);
