<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 06 Mar 2014 11:24:51 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    19 => 
    array (
      'pagetitle' => 'Catálogo',
      'pagetype' => '1',
      'pagelink' => '/pages/Secciones.html',
      'pageparentid' => '0',
      'pageid' => '19',
      'pagecustomersonly' => '0',
    ),
    59 => 
    array (
      'pagetitle' => 'Conócenos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '59',
      'pagecustomersonly' => '0',
    ),
    131 => 
    array (
      'pagetitle' => 'Dónde Comprar',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '131',
      'pagecustomersonly' => '0',
    ),
    123 => 
    array (
      'pagetitle' => 'Inicia Tu Negocio',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '123',
      'pagecustomersonly' => '0',
    ),
    126 => 
    array (
      'pagetitle' => 'Tips de decoración',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '126',
      'pagecustomersonly' => '0',
    ),
    17 => 
    array (
      'pagetitle' => 'Contáctanos',
      'pagetype' => '3',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '17',
      'pagecustomersonly' => '0',
    ),
    45 => 
    array (
      'pagetitle' => 'Aviso De Privacidad',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '45',
      'pagecustomersonly' => '0',
    ),
  ),
  131 => 
  array (
    132 => 
    array (
      'pagetitle' => 'Aguascalientes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '132',
      'pagecustomersonly' => '0',
    ),
    134 => 
    array (
      'pagetitle' => 'Chiapas',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '134',
      'pagecustomersonly' => '0',
    ),
    143 => 
    array (
      'pagetitle' => 'Coahuila',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '143',
      'pagecustomersonly' => '0',
    ),
    135 => 
    array (
      'pagetitle' => 'Distrito Federal',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '135',
      'pagecustomersonly' => '0',
    ),
    147 => 
    array (
      'pagetitle' => 'Estado de México',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '147',
      'pagecustomersonly' => '0',
    ),
    151 => 
    array (
      'pagetitle' => 'Guanajuato',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '151',
      'pagecustomersonly' => '0',
    ),
    136 => 
    array (
      'pagetitle' => 'Hidalgo',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '136',
      'pagecustomersonly' => '0',
    ),
    137 => 
    array (
      'pagetitle' => 'Jalisco',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '137',
      'pagecustomersonly' => '0',
    ),
    138 => 
    array (
      'pagetitle' => 'Michoacán',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '138',
      'pagecustomersonly' => '0',
    ),
    140 => 
    array (
      'pagetitle' => 'Nayarit',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '140',
      'pagecustomersonly' => '0',
    ),
    150 => 
    array (
      'pagetitle' => 'Nuevo León',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '150',
      'pagecustomersonly' => '0',
    ),
    141 => 
    array (
      'pagetitle' => 'Puebla',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '141',
      'pagecustomersonly' => '0',
    ),
    142 => 
    array (
      'pagetitle' => 'San Luis Potosí',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '142',
      'pagecustomersonly' => '0',
    ),
    144 => 
    array (
      'pagetitle' => 'Sinaloa',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '144',
      'pagecustomersonly' => '0',
    ),
    153 => 
    array (
      'pagetitle' => 'Tabasco',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '153',
      'pagecustomersonly' => '0',
    ),
    145 => 
    array (
      'pagetitle' => 'Tamaulipas',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '145',
      'pagecustomersonly' => '0',
    ),
    146 => 
    array (
      'pagetitle' => 'Veracruz',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '131',
      'pageid' => '146',
      'pagecustomersonly' => '0',
    ),
  ),
  126 => 
  array (
    127 => 
    array (
      'pagetitle' => 'Descubre tu Estilo',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '126',
      'pageid' => '127',
      'pagecustomersonly' => '0',
    ),
    128 => 
    array (
      'pagetitle' => 'Combinación de Colores',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '126',
      'pageid' => '128',
      'pagecustomersonly' => '0',
    ),
    129 => 
    array (
      'pagetitle' => 'Elección de Accesorios',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '126',
      'pageid' => '129',
      'pagecustomersonly' => '0',
    ),
    130 => 
    array (
      'pagetitle' => 'Recomendaciones de Lavado',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '126',
      'pageid' => '130',
      'pagecustomersonly' => '0',
    ),
  ),
  59 => 
  array (
    60 => 
    array (
      'pagetitle' => 'Quiénes Somos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '59',
      'pageid' => '60',
      'pagecustomersonly' => '0',
    ),
    61 => 
    array (
      'pagetitle' => 'Nuestros Valores',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '59',
      'pageid' => '61',
      'pagecustomersonly' => '0',
    ),
    62 => 
    array (
      'pagetitle' => 'Nuestra Misión',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '59',
      'pageid' => '62',
      'pagecustomersonly' => '0',
    ),
    63 => 
    array (
      'pagetitle' => 'Nuestra Visión',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '59',
      'pageid' => '63',
      'pagecustomersonly' => '0',
    ),
  ),
  123 => 
  array (
    124 => 
    array (
      'pagetitle' => '¿Porqué elegir Intima Hogar?',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '123',
      'pageid' => '124',
      'pagecustomersonly' => '0',
    ),
    125 => 
    array (
      'pagetitle' => 'Afiliate',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '123',
      'pageid' => '125',
      'pagecustomersonly' => '0',
    ),
    34 => 
    array (
      'pagetitle' => '¡Solicita tu catálogo!',
      'pagetype' => '3',
      'pagelink' => 'http://',
      'pageparentid' => '123',
      'pageid' => '34',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);
