<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 12 Mar 2014 13:42:58 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    560 => 
    array (
      'categoryid' => '560',
      'catparentid' => '0',
      'catname' => 'Recamara',
      'catdepth' => '0',
    ),
    602 => 
    array (
      'categoryid' => '602',
      'catparentid' => '0',
      'catname' => 'Sala',
      'catdepth' => '0',
    ),
    559 => 
    array (
      'categoryid' => '559',
      'catparentid' => '0',
      'catname' => 'Comedor',
      'catdepth' => '0',
    ),
    613 => 
    array (
      'categoryid' => '613',
      'catparentid' => '0',
      'catname' => 'Cocina',
      'catdepth' => '0',
    ),
    565 => 
    array (
      'categoryid' => '565',
      'catparentid' => '0',
      'catname' => 'Baño',
      'catdepth' => '0',
    ),
    578 => 
    array (
      'categoryid' => '578',
      'catparentid' => '0',
      'catname' => 'Básicos',
      'catdepth' => '0',
    ),
    567 => 
    array (
      'categoryid' => '567',
      'catparentid' => '0',
      'catname' => 'Accesorios',
      'catdepth' => '0',
    ),
    655 => 
    array (
      'categoryid' => '655',
      'catparentid' => '0',
      'catname' => 'Hotelería',
      'catdepth' => '0',
    ),
    656 => 
    array (
      'categoryid' => '656',
      'catparentid' => '0',
      'catname' => 'Novedades',
      'catdepth' => '0',
    ),
  ),
  560 => 
  array (
    563 => 
    array (
      'categoryid' => '563',
      'catparentid' => '560',
      'catname' => 'Cobertores',
      'catdepth' => '1',
    ),
    589 => 
    array (
      'categoryid' => '589',
      'catparentid' => '560',
      'catname' => 'Colchas',
      'catdepth' => '1',
    ),
    590 => 
    array (
      'categoryid' => '590',
      'catparentid' => '560',
      'catname' => 'Coordinados de Cuna',
      'catdepth' => '1',
    ),
    622 => 
    array (
      'categoryid' => '622',
      'catparentid' => '560',
      'catname' => 'Duvets',
      'catdepth' => '1',
    ),
    627 => 
    array (
      'categoryid' => '627',
      'catparentid' => '560',
      'catname' => 'Edrecolchas',
      'catdepth' => '1',
    ),
    595 => 
    array (
      'categoryid' => '595',
      'catparentid' => '560',
      'catname' => 'Edredones',
      'catdepth' => '1',
    ),
    561 => 
    array (
      'categoryid' => '561',
      'catparentid' => '560',
      'catname' => 'Fundas y Almohadas Decorativas',
      'catdepth' => '1',
    ),
    632 => 
    array (
      'categoryid' => '632',
      'catparentid' => '560',
      'catname' => 'Sábanas',
      'catdepth' => '1',
    ),
  ),
  563 => 
  array (
    564 => 
    array (
      'categoryid' => '564',
      'catparentid' => '563',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    579 => 
    array (
      'categoryid' => '579',
      'catparentid' => '563',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    583 => 
    array (
      'categoryid' => '583',
      'catparentid' => '563',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  589 => 
  array (
    593 => 
    array (
      'categoryid' => '593',
      'catparentid' => '589',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    617 => 
    array (
      'categoryid' => '617',
      'catparentid' => '589',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    592 => 
    array (
      'categoryid' => '592',
      'catparentid' => '589',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  590 => 
  array (
    594 => 
    array (
      'categoryid' => '594',
      'catparentid' => '590',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  622 => 
  array (
    623 => 
    array (
      'categoryid' => '623',
      'catparentid' => '622',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    624 => 
    array (
      'categoryid' => '624',
      'catparentid' => '622',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
  ),
  627 => 
  array (
    628 => 
    array (
      'categoryid' => '628',
      'catparentid' => '627',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
  595 => 
  array (
    599 => 
    array (
      'categoryid' => '599',
      'catparentid' => '595',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    605 => 
    array (
      'categoryid' => '605',
      'catparentid' => '595',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    625 => 
    array (
      'categoryid' => '625',
      'catparentid' => '595',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  561 => 
  array (
    629 => 
    array (
      'categoryid' => '629',
      'catparentid' => '561',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    621 => 
    array (
      'categoryid' => '621',
      'catparentid' => '561',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
    566 => 
    array (
      'categoryid' => '566',
      'catparentid' => '561',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
  ),
  632 => 
  array (
    633 => 
    array (
      'categoryid' => '633',
      'catparentid' => '632',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    635 => 
    array (
      'categoryid' => '635',
      'catparentid' => '632',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    634 => 
    array (
      'categoryid' => '634',
      'catparentid' => '632',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  602 => 
  array (
    603 => 
    array (
      'categoryid' => '603',
      'catparentid' => '602',
      'catname' => 'Cubre Salas',
      'catdepth' => '1',
    ),
  ),
  559 => 
  array (
    562 => 
    array (
      'categoryid' => '562',
      'catparentid' => '559',
      'catname' => 'Caminos de Mesa',
      'catdepth' => '1',
    ),
    639 => 
    array (
      'categoryid' => '639',
      'catparentid' => '559',
      'catname' => 'Manteles',
      'catdepth' => '1',
    ),
    631 => 
    array (
      'categoryid' => '631',
      'catparentid' => '559',
      'catname' => 'Manteletas',
      'catdepth' => '1',
    ),
  ),
  613 => 
  array (
    626 => 
    array (
      'categoryid' => '626',
      'catparentid' => '613',
      'catname' => 'Accesorios para Cocina',
      'catdepth' => '1',
    ),
    619 => 
    array (
      'categoryid' => '619',
      'catparentid' => '613',
      'catname' => 'Cortinas para Cocina',
      'catdepth' => '1',
    ),
    630 => 
    array (
      'categoryid' => '630',
      'catparentid' => '613',
      'catname' => 'Juegos de Fundas',
      'catdepth' => '1',
    ),
    640 => 
    array (
      'categoryid' => '640',
      'catparentid' => '613',
      'catname' => 'Manteles para Cocina',
      'catdepth' => '1',
    ),
  ),
  565 => 
  array (
    570 => 
    array (
      'categoryid' => '570',
      'catparentid' => '565',
      'catname' => 'Accesorios para Baño',
      'catdepth' => '1',
    ),
    573 => 
    array (
      'categoryid' => '573',
      'catparentid' => '565',
      'catname' => 'Batas de Baño',
      'catdepth' => '1',
    ),
    591 => 
    array (
      'categoryid' => '591',
      'catparentid' => '565',
      'catname' => 'Cortinas para Baño',
      'catdepth' => '1',
    ),
    615 => 
    array (
      'categoryid' => '615',
      'catparentid' => '565',
      'catname' => 'Juegos de Baño',
      'catdepth' => '1',
    ),
    636 => 
    array (
      'categoryid' => '636',
      'catparentid' => '565',
      'catname' => 'Ponchos',
      'catdepth' => '1',
    ),
    650 => 
    array (
      'categoryid' => '650',
      'catparentid' => '565',
      'catname' => 'Salidas de Baño',
      'catdepth' => '1',
    ),
    614 => 
    array (
      'categoryid' => '614',
      'catparentid' => '565',
      'catname' => 'Toallas',
      'catdepth' => '1',
    ),
  ),
  570 => 
  array (
    608 => 
    array (
      'categoryid' => '608',
      'catparentid' => '570',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    571 => 
    array (
      'categoryid' => '571',
      'catparentid' => '570',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    572 => 
    array (
      'categoryid' => '572',
      'catparentid' => '570',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  573 => 
  array (
    574 => 
    array (
      'categoryid' => '574',
      'catparentid' => '573',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    575 => 
    array (
      'categoryid' => '575',
      'catparentid' => '573',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    582 => 
    array (
      'categoryid' => '582',
      'catparentid' => '573',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  591 => 
  array (
    596 => 
    array (
      'categoryid' => '596',
      'catparentid' => '591',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    597 => 
    array (
      'categoryid' => '597',
      'catparentid' => '591',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    606 => 
    array (
      'categoryid' => '606',
      'catparentid' => '591',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  615 => 
  array (
    618 => 
    array (
      'categoryid' => '618',
      'catparentid' => '615',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    620 => 
    array (
      'categoryid' => '620',
      'catparentid' => '615',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  636 => 
  array (
    637 => 
    array (
      'categoryid' => '637',
      'catparentid' => '636',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
  ),
  650 => 
  array (
    654 => 
    array (
      'categoryid' => '654',
      'catparentid' => '650',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
  614 => 
  array (
    638 => 
    array (
      'categoryid' => '638',
      'catparentid' => '614',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    616 => 
    array (
      'categoryid' => '616',
      'catparentid' => '614',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
    653 => 
    array (
      'categoryid' => '653',
      'catparentid' => '614',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    646 => 
    array (
      'categoryid' => '646',
      'catparentid' => '614',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  578 => 
  array (
    580 => 
    array (
      'categoryid' => '580',
      'catparentid' => '578',
      'catname' => 'Almohadas',
      'catdepth' => '1',
    ),
    587 => 
    array (
      'categoryid' => '587',
      'catparentid' => '578',
      'catname' => 'Colchonetas',
      'catdepth' => '1',
    ),
    641 => 
    array (
      'categoryid' => '641',
      'catparentid' => '578',
      'catname' => 'Protectores de Colchón',
      'catdepth' => '1',
    ),
  ),
  641 => 
  array (
    642 => 
    array (
      'categoryid' => '642',
      'catparentid' => '641',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    647 => 
    array (
      'categoryid' => '647',
      'catparentid' => '641',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  567 => 
  array (
    568 => 
    array (
      'categoryid' => '568',
      'catparentid' => '567',
      'catname' => 'Body Pillow',
      'catdepth' => '1',
    ),
    576 => 
    array (
      'categoryid' => '576',
      'catparentid' => '567',
      'catname' => 'Cestos Multiusos',
      'catdepth' => '1',
    ),
    584 => 
    array (
      'categoryid' => '584',
      'catparentid' => '567',
      'catname' => 'Cojines',
      'catdepth' => '1',
    ),
    598 => 
    array (
      'categoryid' => '598',
      'catparentid' => '567',
      'catname' => 'Cortinas',
      'catdepth' => '1',
    ),
    609 => 
    array (
      'categoryid' => '609',
      'catparentid' => '567',
      'catname' => 'Cortineros',
      'catdepth' => '1',
    ),
    600 => 
    array (
      'categoryid' => '600',
      'catparentid' => '567',
      'catname' => 'Cuadros Decorativos',
      'catdepth' => '1',
    ),
    611 => 
    array (
      'categoryid' => '611',
      'catparentid' => '567',
      'catname' => 'Galerías para Ventana',
      'catdepth' => '1',
    ),
    644 => 
    array (
      'categoryid' => '644',
      'catparentid' => '567',
      'catname' => 'Portapañales',
      'catdepth' => '1',
    ),
    648 => 
    array (
      'categoryid' => '648',
      'catparentid' => '567',
      'catname' => 'Tapetes',
      'catdepth' => '1',
    ),
  ),
  576 => 
  array (
    577 => 
    array (
      'categoryid' => '577',
      'catparentid' => '576',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  584 => 
  array (
    585 => 
    array (
      'categoryid' => '585',
      'catparentid' => '584',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    588 => 
    array (
      'categoryid' => '588',
      'catparentid' => '584',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    586 => 
    array (
      'categoryid' => '586',
      'catparentid' => '584',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  600 => 
  array (
    604 => 
    array (
      'categoryid' => '604',
      'catparentid' => '600',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    610 => 
    array (
      'categoryid' => '610',
      'catparentid' => '600',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
    601 => 
    array (
      'categoryid' => '601',
      'catparentid' => '600',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    607 => 
    array (
      'categoryid' => '607',
      'catparentid' => '600',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  611 => 
  array (
    612 => 
    array (
      'categoryid' => '612',
      'catparentid' => '611',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  644 => 
  array (
    645 => 
    array (
      'categoryid' => '645',
      'catparentid' => '644',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  648 => 
  array (
    652 => 
    array (
      'categoryid' => '652',
      'catparentid' => '648',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    651 => 
    array (
      'categoryid' => '651',
      'catparentid' => '648',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    649 => 
    array (
      'categoryid' => '649',
      'catparentid' => '648',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  655 => 
  array (
    662 => 
    array (
      'categoryid' => '662',
      'catparentid' => '655',
      'catname' => 'Cortinas',
      'catdepth' => '1',
    ),
    660 => 
    array (
      'categoryid' => '660',
      'catparentid' => '655',
      'catname' => 'Duvets',
      'catdepth' => '1',
    ),
    661 => 
    array (
      'categoryid' => '661',
      'catparentid' => '655',
      'catname' => 'Sábanas',
      'catdepth' => '1',
    ),
  ),
  660 => 
  array (
    677 => 
    array (
      'categoryid' => '677',
      'catparentid' => '660',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
  661 => 
  array (
    678 => 
    array (
      'categoryid' => '678',
      'catparentid' => '661',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
  656 => 
  array (
    673 => 
    array (
      'categoryid' => '673',
      'catparentid' => '656',
      'catname' => 'Cestos Multiusos',
      'catdepth' => '1',
    ),
    672 => 
    array (
      'categoryid' => '672',
      'catparentid' => '656',
      'catname' => 'Cojines',
      'catdepth' => '1',
    ),
    671 => 
    array (
      'categoryid' => '671',
      'catparentid' => '656',
      'catname' => 'Coordinados de Cuna',
      'catdepth' => '1',
    ),
    670 => 
    array (
      'categoryid' => '670',
      'catparentid' => '656',
      'catname' => 'Cortinas',
      'catdepth' => '1',
    ),
    669 => 
    array (
      'categoryid' => '669',
      'catparentid' => '656',
      'catname' => 'Cuadros Decorativos',
      'catdepth' => '1',
    ),
    665 => 
    array (
      'categoryid' => '665',
      'catparentid' => '656',
      'catname' => 'Edredones',
      'catdepth' => '1',
    ),
    663 => 
    array (
      'categoryid' => '663',
      'catparentid' => '656',
      'catname' => 'Fundas y Almohadas Decorativas',
      'catdepth' => '1',
    ),
    664 => 
    array (
      'categoryid' => '664',
      'catparentid' => '656',
      'catname' => 'Manteles',
      'catdepth' => '1',
    ),
    667 => 
    array (
      'categoryid' => '667',
      'catparentid' => '656',
      'catname' => 'Portapañales',
      'catdepth' => '1',
    ),
    666 => 
    array (
      'categoryid' => '666',
      'catparentid' => '656',
      'catname' => 'Protectores de Colchón',
      'catdepth' => '1',
    ),
    668 => 
    array (
      'categoryid' => '668',
      'catparentid' => '656',
      'catname' => 'Sábanas',
      'catdepth' => '1',
    ),
  ),
  673 => 
  array (
    679 => 
    array (
      'categoryid' => '679',
      'catparentid' => '673',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  672 => 
  array (
    688 => 
    array (
      'categoryid' => '688',
      'catparentid' => '672',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
  671 => 
  array (
    680 => 
    array (
      'categoryid' => '680',
      'catparentid' => '671',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  669 => 
  array (
    681 => 
    array (
      'categoryid' => '681',
      'catparentid' => '669',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    682 => 
    array (
      'categoryid' => '682',
      'catparentid' => '669',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  665 => 
  array (
    683 => 
    array (
      'categoryid' => '683',
      'catparentid' => '665',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
    676 => 
    array (
      'categoryid' => '676',
      'catparentid' => '665',
      'catname' => 'Infantil',
      'catdepth' => '2',
    ),
    675 => 
    array (
      'categoryid' => '675',
      'catparentid' => '665',
      'catname' => 'Juvenil',
      'catdepth' => '2',
    ),
  ),
  663 => 
  array (
    684 => 
    array (
      'categoryid' => '684',
      'catparentid' => '663',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  667 => 
  array (
    685 => 
    array (
      'categoryid' => '685',
      'catparentid' => '667',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  666 => 
  array (
    686 => 
    array (
      'categoryid' => '686',
      'catparentid' => '666',
      'catname' => 'Bebé',
      'catdepth' => '2',
    ),
  ),
  668 => 
  array (
    687 => 
    array (
      'categoryid' => '687',
      'catparentid' => '668',
      'catname' => 'Adulto',
      'catdepth' => '2',
    ),
  ),
);
